---
version: v1.0.0
server:
  port: 8080
  health_check_port: 80
  health_check_path: /healthz
  timeout: 10s
  shutdown_duration: 5s
  tls:
    enabled: true
    cert: _cert_
    key: _key_
    ca: _ca_
